version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/gh"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    groups:
      otel:
        patterns:
        - "*pulumi*"
