linters-settings:
  lll:
    line-length: 180
linters:
  enable-all: true
  disable:
    - exportloopref
    - tagalign
    - gochecknoinits
    - bodyclose
    - depguard
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - ireturn
    - mnd
    - paralleltest
    - varnamelen
    - wrapcheck
    - tagliatelle
