apiVersion: v1
kind: ConfigMap
metadata:
  name: konfig-config
  namespace: standort
data:
  client.yaml: |
    client:
      v1:
        host: konfig.konfig.svc.cluster.local:9090
        user_agent: "Standort/2.0"
        timeout: 1s
        retry:
          timeout: 10s
          attempts: 3
        application: standort
        version: v1.0.0
        environment: production
        continent: '*'
        country: '*'
        command: server
        kind: yaml
        mode: 0o600
    environment: production
    telemetry:
      logger:
        level: info
      metrics:
        kind: otlp
        host: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
        key: env:KONFIG_OTLP_KEY
      tracer:
        kind: otlp
        host: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/traces
        key: env:KONFIG_OTLP_KEY
