apiVersion: apps/v1
kind: Deployment
metadata:
  name: standort
  namespace: standort
spec:
  selector:
    matchLabels:
      app: standort
  replicas: 2
  template:
    metadata:
      labels:
        app: standort
    spec:
      volumes:
        - name: konfig-volume
          configMap:
            name: konfig-config
        - name: standort-volume
          hostPath:
            path: /etc/standort
            type: DirectoryOrCreate
      initContainers:
        - name: standort-init
          image: docker.io/alexfalkowski/konfig:v1.122.0
          args: ["client"]
          volumeMounts:
            - name: konfig-volume
              mountPath: /etc/konfig/client.yaml
              subPath: client.yaml
            - name: standort-volume
              mountPath: /etc/standort
          env:
          - name: KONFIG_CONFIG_FILE
            value: "/etc/konfig/client.yaml"
          - name: KONFIG_APP_CONFIG_FILE
            value: "/etc/standort/server.yaml"
          - name: KONFIG_OTLP_KEY
            valueFrom:
              secretKeyRef:
                name: otlp-secret
                key: token
      containers:
      - name: standort
        image: docker.io/alexfalkowski/standort:v2.83.0
        imagePullPolicy: Always
        args: ["server"]
        volumeMounts:
          - name: standort-volume
            mountPath: /etc/standort
        env:
          - name: STANDORT_CONFIG_FILE
            value: "/etc/standort/server.yaml"
          - name: STANDORT_OTLP_KEY
            valueFrom:
              secretKeyRef:
                name: otlp-secret
                key: token
        ports:
          - containerPort: 8080
          - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            cpu: 125m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: standort
  namespace: standort
  labels:
    app: standort
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: standort
  type: ClusterIP
