apiVersion: apps/v1
kind: Deployment
metadata:
  name: standort
  namespace: standort
spec:
  selector:
    matchLabels:
      app: standort
  replicas: 2
  template:
    metadata:
      labels:
        app: standort
    spec:
      containers:
      - name: standort
        image: docker.io/alexfalkowski/standort:latest
        imagePullPolicy: Always
        args: ["server"]
        env:
          - name: STANDORT_CONFIG_FILE
            value: "yml:CONFIG"
          - name: CONFIG
            value: "ZW52aXJvbm1lbnQ6IHByb2R1Y3Rpb24KY2xpZW50OgogIHYxOgogICAgaG9zdDogbG9jYWxob3N0OjkwOTAKICAgIHVzZXJfYWdlbnQ6ICJTdGFuZG9ydC8xLjAiCiAgICByZXRyeToKICAgICAgdGltZW91dDogMTBzCiAgICAgIGF0dGVtcHRzOiAzCiAgdjI6CiAgICBob3N0OiBsb2NhbGhvc3Q6OTA5MAogICAgdXNlcl9hZ2VudDogIlN0YW5kb3J0LzIuMCIKICAgIHJldHJ5OgogICAgICB0aW1lb3V0OiAxMHMKICAgICAgYXR0ZW1wdHM6IDMKaGVhbHRoOgogIGR1cmF0aW9uOiAxcwogIHRpbWVvdXQ6IDFzCmxpbWl0ZXI6CiAga2luZDogdXNlci1hZ2VudAogIHBhdHRlcm46IDEwMDAtUwpsb2NhdGlvbjoKICBpcDoKICAgIGtpbmQ6IGlwMmxvY2F0aW9uCnRlbGVtZXRyeToKICBsb2dnZXI6CiAgICBsZXZlbDogaW5mbwogIG1ldHJpY3M6CiAgICBraW5kOiBwcm9tZXRoZXVzCnRyYW5zcG9ydDoKICBodHRwOgogICAgcG9ydDogODA4MAogICAgdXNlcl9hZ2VudDogIlN0YW5kb3J0LzIuMCIKICAgIHJldHJ5OgogICAgICB0aW1lb3V0OiAycwogICAgICBhdHRlbXB0czogMwogIGdycGM6CiAgICBwb3J0OiA5MDkwCiAgICB1c2VyX2FnZW50OiAiU3RhbmRvcnQvMi4wIgogICAgcmV0cnk6CiAgICAgIHRpbWVvdXQ6IDJzCiAgICAgIGF0dGVtcHRzOiAzCg=="
        ports:
          - containerPort: 8080
          - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: standort
  namespace: standort
  labels:
    app: standort
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: standort
  type: ClusterIP
