apiVersion: apps/v1
kind: Deployment
metadata:
  name: standort
  namespace: standort
spec:
  selector:
    matchLabels:
      app: standort
  replicas: 2
  template:
    metadata:
      labels:
        app: standort
    spec:
      volumes:
        - name: standort-volume
          configMap:
            name: standort-config
      containers:
      - name: standort
        image: docker.io/alexfalkowski/standort:v2.81.0
        imagePullPolicy: Always
        args: ["server"]
        volumeMounts:
          - name: standort-volume
            mountPath: /etc/standort/server.yaml
            subPath: server.yaml
        env:
          - name: STANDORT_CONFIG_FILE
            value: "/etc/standort/server.yaml"
          - name: STANDORT_OTLP_KEY
            valueFrom:
              secretKeyRef:
                name: otlp-secret
                key: token
        ports:
          - containerPort: 8080
          - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            cpu: 125m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: standort
  namespace: standort
  labels:
    app: standort
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: standort
  type: ClusterIP
