// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: infraops/v2/service.proto

// Schema for infraops "area" configuration files.
//
// Each area under `area/<name>/` has a corresponding `<name>.hjson` file that is decoded into one
// of the top-level messages (Kubernetes, Github, Cloudflare, DigitalOcean). Pulumi programs then
// convert these protobuf messages into internal Go models and provision resources.
//
// Notes:
// - This schema is intentionally configuration-oriented (it models desired state, not provider API objects).
// - For each top-level configuration message, `version` is a config/schema version string used by tooling;
//   it is not necessarily the same as a runtime, provider, or Kubernetes version.

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnvVar defines an environment variable for an application.
//
// The value field supports plain literals as well as repository-specific conventions.
// In particular, the Go implementation treats values prefixed with "secret:" as references
// that are resolved into Kubernetes SecretKeyRefs during deployment.
//
// Secret reference format:
//   - "secret:<secretName>/<key>"
//
// The Kubernetes Secret name used by the implementation is "<secretName>-secret" and the key is <key>.
type EnvVar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the environment variable name (for example "LOG_LEVEL").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value is the environment variable value.
	// If it starts with "secret:", it is interpreted as a secret reference rather than a literal.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_infraops_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Application describes a Kubernetes application to deploy.
//
// This configuration is consumed by the `area/apps` Pulumi program, which creates Kubernetes
// resources such as ServiceAccount, ConfigMap, Deployment, Service, Ingress, and related policies.
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is an optional identifier for the application in configuration.
	// It is available for callers/tools but may not be used by all provisioners.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Kind determines the deployment model for this application.
	// The Go implementation recognizes values like "internal" and "external".
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Name is the Kubernetes resource name base for this application.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace is the Kubernetes namespace to deploy into.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Domain is the external DNS name/host used for ingress routing (for example "api.example.com").
	Domain string `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	// Version is the application version to deploy (for example a container image tag).
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// Resource selects the resource profile to apply to the application pod.
	//
	// Implementation mapping (current):
	//   - "small" (default): cpu 125m-250m, memory 64Mi-128Mi, ephemeral-storage 1Gi-2Gi
	//
	// If an unknown value is provided, the implementation falls back to "small".
	Resource string `protobuf:"bytes,7,opt,name=resource,proto3" json:"resource,omitempty"`
	// Secrets is a list of logical secret names referenced by this application.
	//
	// Clarification:
	//   - This field is an application-level dependency list used by the deployment implementation to
	//     provision and/or wire Secret resources (for example as volumes or other attachments).
	//   - This list is related to, but distinct from, secret references in EnvVars:
	//   - EnvVar values of the form "secret:<secretName>/<key>" reference a specific key within a secret.
	//   - This Secrets list enumerates which logical secrets the application depends on (often the
	//     same <secretName> values), but does not by itself specify which keys are consumed.
	//
	// In the current implementation, these names are typically materialized as Kubernetes Secrets
	// with a "-secret" suffix and are used for volume/env wiring where applicable.
	Secrets []string `protobuf:"bytes,8,rep,name=secrets,proto3" json:"secrets,omitempty"`
	// EnvVars is the list of environment variables to inject into the application container.
	EnvVars       []*EnvVar `protobuf:"bytes,9,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_infraops_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Application) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Application) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Application) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Application) GetSecrets() []string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *Application) GetEnvVars() []*EnvVar {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

// Kubernetes is the top-level configuration for the `area/apps` Pulumi program.
type Kubernetes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version is a configuration/schema version identifier for this file.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Applications is the set of applications to be deployed to the cluster.
	Applications  []*Application `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kubernetes) Reset() {
	*x = Kubernetes{}
	mi := &file_infraops_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kubernetes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes) ProtoMessage() {}

func (x *Kubernetes) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes.ProtoReflect.Descriptor instead.
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{2}
}

func (x *Kubernetes) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Kubernetes) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

// Collaborators toggles whether repository collaborators are managed for a repository.
//
// When enabled, the infra code may create collaborator resources (for example for CI users).
type Collaborators struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled controls whether collaborator resources should be created/managed.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collaborators) Reset() {
	*x = Collaborators{}
	mi := &file_infraops_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collaborators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborators) ProtoMessage() {}

func (x *Collaborators) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborators.ProtoReflect.Descriptor instead.
func (*Collaborators) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *Collaborators) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Template identifies a GitHub template repository.
//
// When provided, a repository may be created from this template rather than as a blank repository.
type Template struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner is the organization or user that owns the template repository.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Repository is the template repository name.
	Repository    string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_infraops_v2_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{4}
}

func (x *Template) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Template) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

// Pages describes GitHub Pages configuration for a repository.
type Pages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled controls whether Pages should be enabled/managed.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Cname is an optional custom domain for the Pages site.
	Cname         string `protobuf:"bytes,2,opt,name=cname,proto3" json:"cname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pages) Reset() {
	*x = Pages{}
	mi := &file_infraops_v2_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pages) ProtoMessage() {}

func (x *Pages) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pages.ProtoReflect.Descriptor instead.
func (*Pages) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{5}
}

func (x *Pages) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Pages) GetCname() string {
	if x != nil {
		return x.Cname
	}
	return ""
}

// Repository describes the desired state of a GitHub repository.
//
// This configuration is consumed by the `area/gh` Pulumi program, which creates the repository
// and applies additional settings such as branch protection, Pages, and collaborators.
type Repository struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the repository name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description is the repository description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// HomepageUrl is the repository homepage URL.
	HomepageUrl string `protobuf:"bytes,3,opt,name=homepage_url,json=homepageUrl,proto3" json:"homepage_url,omitempty"`
	// Visibility is the GitHub visibility string (for example "public" or "private").
	Visibility string `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// IsTemplate marks this repository as a template repository.
	IsTemplate bool `protobuf:"varint,5,opt,name=is_template,json=isTemplate,proto3" json:"is_template,omitempty"`
	// Archived controls whether the repository should be archived.
	Archived bool `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	// Collaborators optionally enables collaborator management for this repository.
	Collaborators *Collaborators `protobuf:"bytes,7,opt,name=collaborators,proto3" json:"collaborators,omitempty"`
	// Template optionally configures a template repository to use when creating this repository.
	Template *Template `protobuf:"bytes,8,opt,name=template,proto3" json:"template,omitempty"`
	// Pages optionally enables/manages GitHub Pages for this repository.
	Pages *Pages `protobuf:"bytes,9,opt,name=pages,proto3" json:"pages,omitempty"`
	// Topics is the set of repository topics to apply.
	Topics []string `protobuf:"bytes,10,rep,name=topics,proto3" json:"topics,omitempty"`
	// Checks is the set of required status check contexts enforced by branch protection.
	//
	// In the current implementation, an empty list is invalid and will cause provisioning to fail.
	Checks        []string `protobuf:"bytes,11,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_infraops_v2_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{6}
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetHomepageUrl() string {
	if x != nil {
		return x.HomepageUrl
	}
	return ""
}

func (x *Repository) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Repository) GetIsTemplate() bool {
	if x != nil {
		return x.IsTemplate
	}
	return false
}

func (x *Repository) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Repository) GetCollaborators() *Collaborators {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

func (x *Repository) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Repository) GetPages() *Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Repository) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Repository) GetChecks() []string {
	if x != nil {
		return x.Checks
	}
	return nil
}

// Github is the top-level configuration for the `area/gh` Pulumi program.
type Github struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version is a configuration/schema version identifier for this file.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Repositories is the set of repositories to create/manage.
	Repositories  []*Repository `protobuf:"bytes,2,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Github) Reset() {
	*x = Github{}
	mi := &file_infraops_v2_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Github) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Github) ProtoMessage() {}

func (x *Github) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Github.ProtoReflect.Descriptor instead.
func (*Github) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{7}
}

func (x *Github) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Github) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// BalancerZone describes a Cloudflare-managed DNS zone for proxied records.
//
// The `area/cf` Pulumi program creates the zone and then creates proxied A/AAAA records for the
// subdomains listed in record_names.
type BalancerZone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the Pulumi resource name prefix for resources created for this zone.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Domain is the apex domain for the zone (for example "example.com").
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// Ipv4 is the IPv4 address used for A records.
	Ipv4 string `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	// Ipv6 is the IPv6 address used for AAAA records.
	Ipv6 string `protobuf:"bytes,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	// RecordNames are subdomain labels (for example ["api", "app"]) used to create records under domain.
	RecordNames   []string `protobuf:"bytes,5,rep,name=record_names,json=recordNames,proto3" json:"record_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalancerZone) Reset() {
	*x = BalancerZone{}
	mi := &file_infraops_v2_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancerZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerZone) ProtoMessage() {}

func (x *BalancerZone) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerZone.ProtoReflect.Descriptor instead.
func (*BalancerZone) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{8}
}

func (x *BalancerZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BalancerZone) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BalancerZone) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *BalancerZone) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *BalancerZone) GetRecordNames() []string {
	if x != nil {
		return x.RecordNames
	}
	return nil
}

// PageZone describes a Cloudflare zone used for a Cloudflare Pages site.
//
// The infra code creates the zone (with strict SSL mode) and creates a proxied CNAME from
// "www.<domain>" to host.
type PageZone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the Pulumi resource name prefix for resources created for this zone.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Domain is the apex domain for the zone (for example "example.com").
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// Host is the Cloudflare Pages hostname to CNAME to (for example "<project>.pages.dev").
	Host          string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageZone) Reset() {
	*x = PageZone{}
	mi := &file_infraops_v2_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageZone) ProtoMessage() {}

func (x *PageZone) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageZone.ProtoReflect.Descriptor instead.
func (*PageZone) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{9}
}

func (x *PageZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageZone) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PageZone) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// BucketZone describes the Cloudflare zone and domain used to attach a custom/public domain to an R2 bucket.
//
// If omitted, the bucket will be created without a custom domain.
type BucketZone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is the Cloudflare zone identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Domain is the fully-qualified domain name to associate with the bucket.
	Domain        string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketZone) Reset() {
	*x = BucketZone{}
	mi := &file_infraops_v2_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketZone) ProtoMessage() {}

func (x *BucketZone) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketZone.ProtoReflect.Descriptor instead.
func (*BucketZone) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{10}
}

func (x *BucketZone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BucketZone) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// Bucket describes a Cloudflare R2 bucket.
//
// If zone is provided, the infra code also provisions an R2 custom domain to expose the bucket publicly.
type Bucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the R2 bucket name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Region is the R2 data location hint (for example "EEUR").
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// Zone is optional; when present, it enables provisioning of an R2 custom domain for the bucket.
	Zone          *BucketZone `protobuf:"bytes,3,opt,name=zone,proto3,oneof" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_infraops_v2_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{11}
}

func (x *Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bucket) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Bucket) GetZone() *BucketZone {
	if x != nil {
		return x.Zone
	}
	return nil
}

// Cloudflare is the top-level configuration for the `area/cf` Pulumi program.
type Cloudflare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version is a configuration/schema version identifier for this file.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// BalancerZones is the set of zones for which proxied A/AAAA records are managed.
	BalancerZones []*BalancerZone `protobuf:"bytes,2,rep,name=balancer_zones,json=balancerZones,proto3" json:"balancer_zones,omitempty"`
	// PageZones is the set of zones configured for Cloudflare Pages sites.
	PageZones []*PageZone `protobuf:"bytes,3,rep,name=page_zones,json=pageZones,proto3" json:"page_zones,omitempty"`
	// Buckets is the set of R2 buckets to create/manage, optionally with custom domains.
	Buckets       []*Bucket `protobuf:"bytes,4,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cloudflare) Reset() {
	*x = Cloudflare{}
	mi := &file_infraops_v2_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cloudflare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cloudflare) ProtoMessage() {}

func (x *Cloudflare) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cloudflare.ProtoReflect.Descriptor instead.
func (*Cloudflare) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{12}
}

func (x *Cloudflare) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Cloudflare) GetBalancerZones() []*BalancerZone {
	if x != nil {
		return x.BalancerZones
	}
	return nil
}

func (x *Cloudflare) GetPageZones() []*PageZone {
	if x != nil {
		return x.PageZones
	}
	return nil
}

func (x *Cloudflare) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// Cluster describes a DigitalOcean Kubernetes cluster to provision.
//
// The `area/do` Pulumi program currently provisions a VPC and then a Kubernetes cluster attached to it.
type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the cluster name used for resource naming.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description is an optional description (used for related resources such as the VPC).
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Resource is a size label (for example "small" or "medium") used to select a droplet size slug.
	Resource      string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_infraops_v2_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{13}
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cluster) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

// DigitalOcean is the top-level configuration for the `area/do` Pulumi program.
type DigitalOcean struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version is a configuration/schema version identifier for this file.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Clusters is the set of Kubernetes clusters to create/manage.
	Clusters      []*Cluster `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalOcean) Reset() {
	*x = DigitalOcean{}
	mi := &file_infraops_v2_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOcean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOcean) ProtoMessage() {}

func (x *DigitalOcean) ProtoReflect() protoreflect.Message {
	mi := &file_infraops_v2_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOcean.ProtoReflect.Descriptor instead.
func (*DigitalOcean) Descriptor() ([]byte, []int) {
	return file_infraops_v2_service_proto_rawDescGZIP(), []int{14}
}

func (x *DigitalOcean) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DigitalOcean) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

var File_infraops_v2_service_proto protoreflect.FileDescriptor

const file_infraops_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x19infraops/v2/service.proto\x12\vinfraops.v2\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xfb\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\a \x01(\tR\bresource\x12\x18\n" +
	"\asecrets\x18\b \x03(\tR\asecrets\x12.\n" +
	"\benv_vars\x18\t \x03(\v2\x13.infraops.v2.EnvVarR\aenvVars\"d\n" +
	"\n" +
	"Kubernetes\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12<\n" +
	"\fapplications\x18\x02 \x03(\v2\x18.infraops.v2.ApplicationR\fapplications\")\n" +
	"\rCollaborators\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"@\n" +
	"\bTemplate\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\"7\n" +
	"\x05Pages\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05cname\x18\x02 \x01(\tR\x05cname\"\x91\x03\n" +
	"\n" +
	"Repository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fhomepage_url\x18\x03 \x01(\tR\vhomepageUrl\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\x12\x1f\n" +
	"\vis_template\x18\x05 \x01(\bR\n" +
	"isTemplate\x12\x1a\n" +
	"\barchived\x18\x06 \x01(\bR\barchived\x12@\n" +
	"\rcollaborators\x18\a \x01(\v2\x1a.infraops.v2.CollaboratorsR\rcollaborators\x121\n" +
	"\btemplate\x18\b \x01(\v2\x15.infraops.v2.TemplateR\btemplate\x12(\n" +
	"\x05pages\x18\t \x01(\v2\x12.infraops.v2.PagesR\x05pages\x12\x16\n" +
	"\x06topics\x18\n" +
	" \x03(\tR\x06topics\x12\x16\n" +
	"\x06checks\x18\v \x03(\tR\x06checks\"_\n" +
	"\x06Github\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12;\n" +
	"\frepositories\x18\x02 \x03(\v2\x17.infraops.v2.RepositoryR\frepositories\"\x85\x01\n" +
	"\fBalancerZone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x04 \x01(\tR\x04ipv6\x12!\n" +
	"\frecord_names\x18\x05 \x03(\tR\vrecordNames\"J\n" +
	"\bPageZone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\"4\n" +
	"\n" +
	"BucketZone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"o\n" +
	"\x06Bucket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x120\n" +
	"\x04zone\x18\x03 \x01(\v2\x17.infraops.v2.BucketZoneH\x00R\x04zone\x88\x01\x01B\a\n" +
	"\x05_zone\"\xcd\x01\n" +
	"\n" +
	"Cloudflare\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12@\n" +
	"\x0ebalancer_zones\x18\x02 \x03(\v2\x19.infraops.v2.BalancerZoneR\rbalancerZones\x124\n" +
	"\n" +
	"page_zones\x18\x03 \x03(\v2\x15.infraops.v2.PageZoneR\tpageZones\x12-\n" +
	"\abuckets\x18\x04 \x03(\v2\x13.infraops.v2.BucketR\abuckets\"[\n" +
	"\aCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"Z\n" +
	"\fDigitalOcean\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x120\n" +
	"\bclusters\x18\x02 \x03(\v2\x14.infraops.v2.ClusterR\bclustersB6Z4github.com/alexfalkowski/infraops/v2/api/infraops/v2b\x06proto3"

var (
	file_infraops_v2_service_proto_rawDescOnce sync.Once
	file_infraops_v2_service_proto_rawDescData []byte
)

func file_infraops_v2_service_proto_rawDescGZIP() []byte {
	file_infraops_v2_service_proto_rawDescOnce.Do(func() {
		file_infraops_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infraops_v2_service_proto_rawDesc), len(file_infraops_v2_service_proto_rawDesc)))
	})
	return file_infraops_v2_service_proto_rawDescData
}

var file_infraops_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_infraops_v2_service_proto_goTypes = []any{
	(*EnvVar)(nil),        // 0: infraops.v2.EnvVar
	(*Application)(nil),   // 1: infraops.v2.Application
	(*Kubernetes)(nil),    // 2: infraops.v2.Kubernetes
	(*Collaborators)(nil), // 3: infraops.v2.Collaborators
	(*Template)(nil),      // 4: infraops.v2.Template
	(*Pages)(nil),         // 5: infraops.v2.Pages
	(*Repository)(nil),    // 6: infraops.v2.Repository
	(*Github)(nil),        // 7: infraops.v2.Github
	(*BalancerZone)(nil),  // 8: infraops.v2.BalancerZone
	(*PageZone)(nil),      // 9: infraops.v2.PageZone
	(*BucketZone)(nil),    // 10: infraops.v2.BucketZone
	(*Bucket)(nil),        // 11: infraops.v2.Bucket
	(*Cloudflare)(nil),    // 12: infraops.v2.Cloudflare
	(*Cluster)(nil),       // 13: infraops.v2.Cluster
	(*DigitalOcean)(nil),  // 14: infraops.v2.DigitalOcean
}
var file_infraops_v2_service_proto_depIdxs = []int32{
	0,  // 0: infraops.v2.Application.env_vars:type_name -> infraops.v2.EnvVar
	1,  // 1: infraops.v2.Kubernetes.applications:type_name -> infraops.v2.Application
	3,  // 2: infraops.v2.Repository.collaborators:type_name -> infraops.v2.Collaborators
	4,  // 3: infraops.v2.Repository.template:type_name -> infraops.v2.Template
	5,  // 4: infraops.v2.Repository.pages:type_name -> infraops.v2.Pages
	6,  // 5: infraops.v2.Github.repositories:type_name -> infraops.v2.Repository
	10, // 6: infraops.v2.Bucket.zone:type_name -> infraops.v2.BucketZone
	8,  // 7: infraops.v2.Cloudflare.balancer_zones:type_name -> infraops.v2.BalancerZone
	9,  // 8: infraops.v2.Cloudflare.page_zones:type_name -> infraops.v2.PageZone
	11, // 9: infraops.v2.Cloudflare.buckets:type_name -> infraops.v2.Bucket
	13, // 10: infraops.v2.DigitalOcean.clusters:type_name -> infraops.v2.Cluster
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_infraops_v2_service_proto_init() }
func file_infraops_v2_service_proto_init() {
	if File_infraops_v2_service_proto != nil {
		return
	}
	file_infraops_v2_service_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infraops_v2_service_proto_rawDesc), len(file_infraops_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infraops_v2_service_proto_goTypes,
		DependencyIndexes: file_infraops_v2_service_proto_depIdxs,
		MessageInfos:      file_infraops_v2_service_proto_msgTypes,
	}.Build()
	File_infraops_v2_service_proto = out.File
	file_infraops_v2_service_proto_goTypes = nil
	file_infraops_v2_service_proto_depIdxs = nil
}
