checks:
  doNotAutoAddDefaults: true
  include:
    - "access-to-create-pods"
    - "access-to-secrets"
    - "cluster-admin-role-binding"
    - "dangling-horizontalpodautoscaler"
    - "dangling-ingress"
    - "dangling-networkpolicy"
    - "dangling-networkpolicypeer-podselector"
    - "dangling-service"
    - "dangling-servicemonitor"
    #- "default-service-account"
    - "deprecated-service-account-field"
    #- "dnsconfig-options"
    - "docker-sock"
    - "drop-net-raw-capability"
    - "duplicate-env-var"
    - "env-var-secret"
    - "exposed-services"
    - "host-ipc"
    - "host-network"
    - "host-pid"
    - "hpa-minimum-three-replicas"
    - "invalid-target-ports"
    - "latest-tag"
    - "liveness-port"
    #- "minimum-three-replicas"
    - "mismatching-selector"
    #- "no-anti-affinity"
    - "no-extensions-v1beta"
    - "no-liveness-probe"
    #- "no-node-affinity"
    #- "no-read-only-root-fs"
    - "no-readiness-probe"
    #- "no-rolling-update-strategy"
    - "non-existent-service-account"
    #- "non-isolated-pod"
    - "pdb-max-unavailable"
    - "pdb-min-available"
    - "privilege-escalation-container"
    - "privileged-container"
    - "privileged-ports"
    #- "read-secret-from-env-var"
    - "readiness-port"
    #- "required-annotation-email"
    #- "required-label-owner"
    #- "run-as-non-root"
    - "scc-deny-privileged-container"
    - "sensitive-host-mounts"
    - "ssh-port"
    - "startup-port"
    - "unsafe-proc-mount"
    - "unsafe-sysctls"
    #- "unset-cpu-requirements"
    #- "unset-memory-requirements"
    - "use-namespace"
    - "wildcard-in-rules"
    #- "writable-host-mount"

