version: "2.0"
applications: [
  {
    id: "1115c470-ccc9-4daf-8459-ef1e19c40afe"
    kind: "internal"
    name: "konfig"
    namespace: "lean"
    domain: "lean-thoughts.com"
    version: "1.533.0"
    resources: {
      cpu: {
        min: "250m"
        max: "500m"
      }
      memory: {
        min: "128Mi"
        max: "256Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp", "gh", "konfig"]
  },
  {
    id: "98968ca0-4ada-4856-8547-210f92b838ea"
    kind: "internal"
    name: "bezeichner"
    namespace: "lean"
    domain: "lean-thoughts.com"
    init_version: "0.245.0"
    version: "1.402.0"
    config_version: "1.15.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp", "konfig"]
  },
  {
    id: "28c679dc-5924-47e8-ac48-73cd842ba5cd"
    kind: "internal"
    name: "standort"
    namespace: "lean"
    domain: "lean-thoughts.com"
    init_version: "0.245.0"
    version: "2.396.0"
    config_version: "1.16.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp", "konfig"]
  },
  {
    id: "b46608ae-950a-46bb-b37a-4dfe68a95b52"
    kind: "internal"
    name: "web"
    namespace: "lean"
    domain: "lean-thoughts.com"
    init_version: "0.245.0"
    version: "0.270.0"
    config_version: "1.6.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp", "konfig"]
  },
  {
    kind: "external"
    name: "monitoror"
    namespace: "lean"
    domain: "lean-thoughts.com"
    version: "1.2"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    environments: [
      {
        name: "MO_MONITORABLE_GITHUB_TOKEN"
        value: "secret:gh/token"
      }
    ]
  }
]
