version: "2.0"
applications: [
  {
    id: "98968ca0-4ada-4856-8547-210f92b838ea"
    kind: "internal"
    name: "bezeichner"
    namespace: "lean"
    domain: "lean-thoughts.com"
    version: "1.441.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp"]
  },
  {
    id: "28c679dc-5924-47e8-ac48-73cd842ba5cd"
    kind: "internal"
    name: "standort"
    namespace: "lean"
    domain: "lean-thoughts.com"
    version: "2.436.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp"]
  },
  {
    id: "b46608ae-950a-46bb-b37a-4dfe68a95b52"
    kind: "internal"
    name: "web"
    namespace: "lean"
    domain: "lean-thoughts.com"
    version: "1.6.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp"]
  },
  {
    id: "f115d2ee-0700-47be-a423-830bee7750b2"
    kind: "internal"
    name: "sasha"
    namespace: "lean"
    domain: "sasha-adventures.com"
    version: "1.8.0"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    secrets: ["otlp"]
  },
  {
    kind: "external"
    name: "monitoror"
    namespace: "lean"
    domain: "lean-thoughts.com"
    version: "1.10"
    resources: {
      cpu: {
        min: "125m"
        max: "250m"
      }
      memory: {
        min: "64Mi"
        max: "128Mi"
      }
      storage: {
        min: "1Gi"
        max: "2Gi"
      }
    }
    environments: [
      {
        name: "MO_MONITORABLE_GITHUB_TOKEN"
        value: "secret:gh/token"
      }
    ]
  }
]
