alloy:
  configMap:
    create: true
  clustering:
    enabled: false
  controller:
    type: "daemonset"
  mounts:
    # -- Mount /var/log from the host into the container for log collection.
    varlog: true
