version: "2.0"
balancer_zones: [
  {
    name: "lean-thoughts"
    domain: "lean-thoughts.com"
    record_names: ["konfig", "standort", "bezeichner", "web", "monitoror"]
    ipv4: "67.207.76.131"
    ipv6: "2a03:b0c0:3:f0::edba:5000"
  },
  {
    name: "sasha-adventures"
    domain: "sasha-adventures.com"
    record_names: ["sasha"]
    ipv4: "67.207.76.131"
    ipv6: "2a03:b0c0:3:f0::edba:5000"
  }
]
page_zones: [
  {
    name:   "afalkowski"
    domain: "afalkowski.com"
    host:   "alexfalkowski.github.io"
  }
]
buckets: [
  {
    name: "sasha-cms"
    region: "EEUR"
    zone: {
      id: "9e3c6c5da8f6e067f960629d1d099e93"
      domain: "cms.sasha-adventures.com"
    }
  }
]
