version: "2.0"
repositories: {
  name: "alexfalkowski.github.io"
  description: "A site for my profile."
  homepage_url: "https://alexfalkowski.github.io"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
    cname: "www.afalkowski.com"
  }
  topics: "jekyll"
  topics: "ruby"
  checks: "ci/circleci: build"
}
repositories: {
  name: "nonnative"
  description: "Allows you to keep using the power of ruby to test other systems."
  homepage_url: "https://alexfalkowski.github.io/nonnative"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "ruby"
  topics: "cucumber"
  topics: "bdd"
  checks: "ci/circleci: build"
}
repositories: {
  name: "go-service"
  description: "A framework to build services in go."
  homepage_url: "https://alexfalkowski.github.io/go-service"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "grpc"
  topics: "http"
  topics: "rpc"
  topics: "mvc"
  topics: "postgres"
  topics: "cache"
  topics: "redis"
  topics: "cloudevents"
  checks: "ci/circleci: build"
}
repositories: {
  name: "go-health"
  description: "Health monitoring pattern in go."
  homepage_url: "https://alexfalkowski.github.io/go-health"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "k8s"
  checks: "ci/circleci: build"
}
repositories: {
  name: "infraops"
  description: "A place where all infrastructure is taken care of."
  homepage_url: "https://alexfalkowski.github.io/infraops"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "cloudflare"
  topics: "digitalocean"
  topics: "github"
  topics: "k8s"
  checks: "ci/circleci: build"
}
repositories: {
  name: "bin"
  description: "A place for common executables."
  homepage_url: "https://alexfalkowski.github.io/bin"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "bash"
  topics: "ruby"
  topics: "docker"
  checks: "ci/circleci: build"
}
repositories: {
  name: "scripts"
  description: "A place for common scripts."
  homepage_url: "https://alexfalkowski.github.io/scripts"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "bash"
  checks: "ci/circleci: lint"
}
repositories: {
  name: "app-config"
  description: "A place for all of my application configuration."
  homepage_url: "https://alexfalkowski.github.io/app-config"
  visibility: "public"
  archived: true
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  checks: "ci/circleci: verify-config"
}
repositories: {
  name: "docker"
  description: "Common setup used for my projects."
  homepage_url: "https://alexfalkowski.github.io/docker"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "docker"
  topics: "ruby"
  topics: "golang"
  checks: "ci/circleci: lint"
}
repositories: {
  name: "go-client-template"
  description: "A template for go clients."
  homepage_url: "https://alexfalkowski.github.io/go-client-template"
  visibility: "public"
  is_template: true
  collaborators: {
    enabled: true
  }
  template: {
    owner: "alexfalkowski"
    repository: "go-service-template"
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  checks: "ci/circleci: build-client"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "go-service-template"
  description: "A template for go services."
  homepage_url: "https://alexfalkowski.github.io/go-service-template"
  visibility: "public"
  is_template: true
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  topics: "microservice"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "bezeichner"
  description: "Bezeichner takes care of identifiers used in your services."
  homepage_url: "https://alexfalkowski.github.io/bezeichner"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "konfigctl"
  description: "A tool to control https://alexfalkowski.github.io/konfig."
  homepage_url: "https://alexfalkowski.github.io/konfigctl"
  visibility: "public"
  archived: true
  collaborators: {
    enabled: true
  }
  template: {
    owner: "alexfalkowski"
    repository: "go-client-template"
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  checks: "ci/circleci: build-client"
  checks: "ci/circleci: build-docker"
}
repositories: {
  name: "konfig"
  description: "Konfig is a configuration system for application configuration."
  homepage_url: "https://alexfalkowski.github.io/konfig"
  visibility: "public"
  archived: true
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker"
  checks: "ci/circleci: features-grpc"
  checks: "ci/circleci: features-http"
  checks: "ci/circleci: features-coverage"
}
repositories: {
  name: "migrieren"
  description: "Migrieren provides a way to migrate your databases."
  homepage_url: "https://alexfalkowski.github.io/migrieren"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "standort"
  description: "Standort provides location based information."
  homepage_url: "https://alexfalkowski.github.io/standort"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "status"
  description: "An alternative to https://httpstat.us/."
  homepage_url: "https://alexfalkowski.github.io/status"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "web"
  description: "A website lean-thoughts.com."
  homepage_url: "https://alexfalkowski.github.io/web"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  template: {
    owner: "alexfalkowski"
    repository: "go-service-template"
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  topics: "htmx"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "sashactl"
  description: "A tool that provides a workflow for https://alexfalkowski.github.io/sasha."
  homepage_url: "https://alexfalkowski.github.io/sashactl"
  visibility: "public"
  archived: true
  collaborators: {
    enabled: true
  }
  template: {
    owner: "alexfalkowski"
    repository: "go-client-template"
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  topics: "r2"
  topics: "aws"
  topics: "s3"
  checks: "ci/circleci: build-client"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "sasha"
  description: "Sasha is site for recording of awesome adventures."
  homepage_url: "https://alexfalkowski.github.io/sasha"
  visibility: "public"
  archived: true
  collaborators: {
    enabled: true
  }
  template: {
    owner: "alexfalkowski"
    repository: "go-service-template"
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  topics: "htmx"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "go-monolith"
  description: "A template to have a distributed monolith."
  homepage_url: "https://alexfalkowski.github.io/go-monolith"
  visibility: "public"
  is_template: true
  collaborators: {
    enabled: true
  }
  template: {
    owner: "alexfalkowski"
    repository: "go-service-template"
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "ruby"
  topics: "make"
  topics: "cucumber"
  topics: "monolith"
  checks: "ci/circleci: build-service"
  checks: "ci/circleci: build-docker-amd64"
  checks: "ci/circleci: build-docker-arm64"
}
repositories: {
  name: "tausch"
  description: "A stub for https://pkg.go.dev/os/exec."
  homepage_url: "https://alexfalkowski.github.io/tausch"
  visibility: "public"
  collaborators: {
    enabled: true
  }
  pages: {
    enabled: true
  }
  topics: "golang"
  topics: "stub"
  topics: "test"
  checks: "ci/circleci: build"
}
